### ISSUE TITLE
Transformation axis can't be specified

### ISSUE THREAD

**Issue by svenkleinert** [etfrogers/pyhank#29]
Thanks for this nice library. Unfortunately, there is an option missing to specify the axis of an array that should be transformed. This leads to some ugly code if you use cylindrical coordinates. For example a 3D array `A` containing 2D fields sampled along a propagation direction requires the following to transform it to frequency space:
`import numpy as np`
`A_f = np.array( [ np.fft.fft( ht.qdht( A[i,:,:] ), axis=1 ) for i in range( A.shape[0] ) ] )`,
where `ht` is a HankelTransform object.

An option to specify the axis (like for the numpy/scipy fft) would transform it into the following:
`A_f = np.fft.fft( ht.qdht( A, axis=1 ), axis=2 ) )`

This means:
1. only 1D or 2D arrays can be transformed
2. 2D arrays can only be transformed along axis=0

I'll send you a pull request soon that should solve these problems.

**Comment by etfrogers** [comment]
Closed by #30
